### ISSUE TITLE
[Android][Crash] 

### ISSUE THREAD

**Issue by Tourmen** [mousebird/WhirlyGlobe#1020]
I try to re-use a view `globeController.getContentView()` and do not re-create new WhirlyGlobe instance working with my application.
Doing this (f.e.) I can keep an instance of WG in MainActivity and then try to walk through several Android fragments.
I do `addView(whirlyGlobeView)` and `removeAllViews()` on a fragment creating and destroying fragment's view. And for the 1st time it is ok. I am able to show WG view. But when I try to re-use  it and open another fragment with WG view, I constantly get a crash related to: 
at **com.mousebird.maply.LayerThread$2.run(LayerThread.java:165)**

 --------- beginning of crash

```
12-20 17:20:28.382 4647-4647/com.example.anton.testwg E/AndroidRuntime: 
FATAL EXCEPTION: main
                                                                        
Process: com.example.anton.testwg, PID: 4647

java.lang.IllegalMonitorStateException
at java.util.concurrent.locks.ReentrantLock$Sync.tryRelease(ReentrantLock.java:126)
at java.util.concurrent.locks.AbstractQueuedSynchronizer.release(AbstractQueuedSynchronizer.java:1260)
at java.util.concurrent.locks.ReentrantLock.unlock(ReentrantLock.java:434)
at com.mousebird.maply.LayerThread$2.run(LayerThread.java:165)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6780)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)

**Comment by GolubRoman** [comment]
I have the same issue. I tried to use map fragment in two places, but this views are not bound in any way. I don't understand why I'm getting such exception. Please, owners, help

**Comment by mousebird** [comment]
So there is a Fragment implemented in the toolkit.  I would rather toolkit users use that Fragment than try to reuse the content view.

**Comment by CurtesMalteser** [comment]
There are update about this issue? App still crashing even when 

> toolkit users use that Fragment than try to reuse the content view.

**Comment by mousebird** [comment]
At this point I'd prefer developers use the Fragment.  I was able to resolve all the various cleanup issues in that code.  Is there a compelling reason to not use the Fragment?

**Comment by CurtesMalteser** [comment]
Yes, I'm asking your help on 
https://github.com/mousebird/WhirlyGlobe/issues/1163
to understand how to make a custom view for RecyclerView.
