### ISSUE TITLE
[Android] Add Vector Null Pointer

### ISSUE THREAD

**Issue by cristianabraga** [mousebird/WhirlyGlobe#1157]
Hi, I am trying to exercise with your android tutorials and after "Vector Data" tutorial I've got the previous error:  
java.lang.NullPointerException: Attempt to invoke virtual method 'com.mousebird.maply.ComponentObject com.mousebird.maply.MaplyBaseController.addVector(com.mousebird.maply.VectorObject, com.mousebird.maply.VectorInfo, com.mousebird.maply.MaplyBaseController$ThreadMode)' on a null object reference
        at com.example.dissertation.GeoJsonHttpTask.onPostExecute(GeoJsonHttpTask.java:56)
        at com.example.dissertation.GeoJsonHttpTask.onPostExecute(GeoJsonHttpTask.java:14)
        at android.os.AsyncTask.finish(AsyncTask.java:695)
        at android.os.AsyncTask.-wrap1(Unknown Source:0)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Disconnected from the target VM, address: 'localhost:8618', transport: 'socket'

The error from line 14 is at public class GeoJsonHttpTask extends AsyncTask<String, Void, String> and line 57 when I am adding the vector:  controller.addVector.

Any idea what it could be? 

Thanks a lot in advance.

**Comment by mousebird** [comment]
That suggests your MapController or GlobeController is null in your GeoJsonHTTPTask.

**Comment by cristianabraga** [comment]
Guys, really thanks for your quick answer. I was using a GlobeController, but in GeoJsonHTTPTask I've set MapController. Sorry for my foolish question :)

**Comment by mousebird** [comment]
No worries.  Easy questions are better than hard ones.
