### ISSUE TITLE
[Android] Crash when querying globe.getCurrentViewGeo() when completely zoomed out

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#577]
When calling globe.getCurrentViewGeo() and the one of the corner of the view is not on earth (very zoomed out), there is a crash with the following message 
```
java.lang.NullPointerException: Attempt to invoke virtual method 'double com.mousebird.maply.Point2d.getX()' on a null object reference
                                                                                        at com.mousebird.maply.Point2d.<init>(Point2d.java:48)
                                                                                        at com.mousebird.maply.Mbr.addPoint(Mbr.java:86)
                                                                                        at com.mousebird.maply.GlobeController.getCurrentViewGeo(GlobeController.java:210)
```

I have integrated a test case in the AutoTester (MBTilesImageTestCase), commit is [here](https://github.com/ironbird-software/WhirlyGlobe/commit/3ecfd08d3df38a483e2c527d797a9638bfc81b4e).

Will create a PR so that you can easily reproduce it.

**Comment by darenig** [comment]
I'm also seeing this crash.

**Comment by mousebird** [comment]
Should now be fixed.
