### ISSUE TITLE
[Android] New instance of crash

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#664]
Got this
```
07-14 17:43:27.795 6135-6145/com.droidfav2 A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x3f800004 in tid 6145 (FinalizerDaemon)
07-14 17:43:27.856 12458-12458/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
07-14 17:43:27.856 12458-12458/? A/DEBUG: Build fingerprint: 'google/volantis/flounder:6.0.1/MOB30M/2862625:user/release-keys'
07-14 17:43:27.856 12458-12458/? A/DEBUG: Revision: '0'
07-14 17:43:27.856 12458-12458/? A/DEBUG: ABI: 'arm'
07-14 17:43:27.857 12458-12458/? A/DEBUG: pid: 6135, tid: 6145, name: FinalizerDaemon  >>> com.droidfav2 <<<
07-14 17:43:27.857 12458-12458/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x3f800004
07-14 17:43:27.880 12458-12458/? A/DEBUG:     r0 b5445840  r1 f44b1510  r2 3f800004  r3 b52232d8
07-14 17:43:27.881 12458-12458/? A/DEBUG:     r4 ddf18c4c  r5 6f7b9b0c  r6 6fce7fa8  r7 6fce7fa8
07-14 17:43:27.881 12458-12458/? A/DEBUG:     r8 6fce7800  r9 ab281a10  sl 12fec5b0  fp 13239a00
07-14 17:43:27.881 12458-12458/? A/DEBUG:     ip f6f525dc  sp f44b1500  lr dddd7331  pc dddd5224  cpsr 000f0030
07-14 17:43:27.923 12458-12458/? A/DEBUG: backtrace:
07-14 17:43:27.923 12458-12458/? A/DEBUG:     #00 pc 007bd224  /data/app/com.droidfav2-2/lib/arm/libMaply.so (_ZN9WhirlyKit13VectorManagerD2Ev+63)
07-14 17:43:27.923 12458-12458/? A/DEBUG:     #01 pc 007bd2b5  /data/app/com.droidfav2-2/lib/arm/libMaply.so (_ZN9WhirlyKit13VectorManagerD0Ev+8)
07-14 17:43:27.923 12458-12458/? A/DEBUG:     #02 pc 00751909  /data/app/com.droidfav2-2/lib/arm/libMaply.so (_ZN9WhirlyKit5SceneD2Ev+276)
07-14 17:43:27.923 12458-12458/? A/DEBUG:     #03 pc 00723fd5  /data/app/com.droidfav2-2/lib/arm/libMaply.so (_ZN5Maply8MapSceneD1Ev+24)
07-14 17:43:27.923 12458-12458/? A/DEBUG:     #04 pc 00724001  /data/app/com.droidfav2-2/lib/arm/libMaply.so (_ZN5Maply8MapSceneD0Ev+8)
07-14 17:43:27.923 12458-12458/? A/DEBUG:     #05 pc 007e6aeb  /data/app/com.droidfav2-2/lib/arm/libMaply.so (Java_com_mousebird_maply_MapScene_dispose+54)
07-14 17:43:27.924 12458-12458/? A/DEBUG:     #06 pc 01dc48af  /data/app/com.droidfav2-2/oat/arm/base.odex (offset 0xd8b000) (void com.mousebird.maply.MapScene.dispose()+74)
07-14 17:43:27.924 12458-12458/? A/DEBUG:     #07 pc 01dc4925  /data/app/com.droidfav2-2/oat/arm/base.odex (offset 0xd8b000) (void com.mousebird.maply.MapScene.finalize()+48)
07-14 17:43:27.924 12458-12458/? A/DEBUG:     #08 pc 722a7819  /data/dalvik-cache/arm/system@framework@boot.oat (offset 0x1ec9000)
07-14 17:43:28.524 12458-12458/? A/DEBUG: Tombstone written to: /data/tombstones/tombstone_00
07-14 17:43:28.525 12458-12458/? E/DEBUG: AM write failed: Broken pipe
07-14 17:43:29.383 19764-26141/? E/DropBoxTask: null InputStream
                                                java.io.IOException: null InputStream
                                                    at wtd.a(:com.google.android.gms:182)
                                                    at wtd.b(:com.google.android.gms:124)
                                                    at wsi.a(:com.google.android.gms:88)
                                                    at com.google.android.gms.stats.service.DropBoxEntryAddedChimeraService.onHandleIntent(:com.google.android.gms:1176)
                                                    at bdz.handleMessage(:com.google.android.gms:65)
                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                    at android.os.Looper.loop(Looper.java:148)
                                                    at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by mousebird** [comment]
This should be fixed.  Or at least the explicit shutdown of the Scene should move the problem elsewhere.

Let's group new FinalizerDaemon crashes into their own single issue.  Nothing should be cleaned up in the Finalizer Daemon at this point.  So if we see something, I'll need to explicitly shut it down.
