### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by coderLeng** [mousebird/WhirlyGlobe#679]
` Process: com.**.app.android, PID: 11507
                                                                          java.lang.UnsatisfiedLinkError: No implementation found for void com.mousebird.maply.ParticleSystemManager.nativeInit() (tried Java_com_mousebird_maply_ParticleSystemManager_nativeInit and Java_com_mousebird_maply_ParticleSystemManager_nativeInit__)
                                                                              at com.mousebird.maply.ParticleSystemManager.nativeInit(Native Method)
                                                                              at com.mousebird.maply.ParticleSystemManager.<clinit>(ParticleSystemManager.java:53)
                                                                              at com.mousebird.maply.MaplyBaseController.Init(MaplyBaseController.java:225)
                                                                              at com.mousebird.maply.GlobeController.Init(GlobeController.java:89)
                                                                              at com.mousebird.maply.GlobeController.<init>(GlobeController.java:63)
                                                                              at com.**.app.android.fragment.WhirlyGlobeFragment.onCreateView(WhirlyGlobeFragment.java:90)
                                                                              at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)
                                                                              at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
                                                                              at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
                                                                              at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:742)
                                                                              at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
                                                                              at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:339)
                                                                              at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:601)
                                                                              at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1238)
                                                                              at android.app.Activity.performStart(Activity.java:6327)
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2395)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2492)
                                                                              at android.app.ActivityThread.access$900(ActivityThread.java:153)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1358)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:148)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5459)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)`

Who met this kind of situation?

**Comment by mousebird** [comment]
Could be it's not finding the Maply .so.
Or it could be a confused .so.  I did just change some of the build settings.

Are you building it yourself or using a binary?

**Comment by coderLeng** [comment]
Thank you very much,i find the problem . It works well ,after i delete libMaply.so. @mousebird
