### ISSUE TITLE
Android app crashes when using Texture view and setting the background color to transparent

### ISSUE THREAD

**Issue by sonyraj** [mousebird/WhirlyGlobe#685]
@mousebird As you haev mentioned in a comment in [Red color and light issue] (https://github.com/mousebird/WhirlyGlobe/issues/661)  I've changed the code to 

`       settings.useSurfaceView = false;        
 settings.clearColor = ContextCompat.getColor(getActivity(), android.R.color.transparent);
        mGlobeController = new GlobeController(getActivity(), settings);`

But it is throwing Runtime exception here is the stack-trace
`E/AndroidRuntime: FATAL EXCEPTION: GLThread 234
                                                                        Process: com.xtronlabs.map_test, PID: 2694
                                                                        java.lang.RuntimeException: createContext failed: 12293
                                                                            at com.mousebird.maply.GLTextureView$EglHelper.throwEglException(GLTextureView.java:1142)
                                                                            at com.mousebird.maply.GLTextureView$EglHelper.throwEglException(GLTextureView.java:1134)
                                                                            at com.mousebird.maply.GLTextureView$EglHelper.start(GLTextureView.java:999)
                                                                            at com.mousebird.maply.GLTextureView$GLThread.guardedRun(GLTextureView.java:1329)
                                                                            at com.mousebird.maply.GLTextureView$GLThread.run(GLTextureView.java:1183)
` 
Testing device is dell venue 7 hspa+ 
Chip set : Intel Atom Z2560
CPU : Dual-core 1.6 GHz
GPU : PowerVR SGX544MP2

**Comment by mousebird** [comment]
Better stick with the SurfaceView, then.  I'll make a note of the TextureView problem, but it may be hard to test.

**Comment by sonyraj** [comment]
Thank you :+1:
