### ISSUE TITLE
[Android] Non finalizer related crash

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#697]
An instance of crash that came from Crashalytics:

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'com.mousebird.maply.ComponentObject[] com.mousebird.maply.VectorStyle.buildObjects(java.util.List, com.mousebird.maply.MaplyTileID, com.mousebird.maply.MaplyBaseController)' on a null object reference
       at com.mousebird.maply.MapboxVectorTileSource$1.run(MapboxVectorTileSource.java:134)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by mousebird** [comment]
Put in guard code.  Not sure why this would happen, though.

**Comment by msgrasser** [comment]
I'm receiving this same error.

```
FATAL EXCEPTION: External Maply Layer Thread
    java.lang.NullPointerException: Attempt to invoke interface method 'com.mousebird.maply.ComponentObject[] com.mousebird.maply.VectorStyle.buildObjects(java.util.List, com.mousebird.maply.MaplyTileID, com.mousebird.maply.MaplyBaseController)' on a null object reference
    at com.mousebird.maply.MapboxVectorTileSource$1.run(MapboxVectorTileSource.java:134)
    at android.os.Handler.handleCallback(Handler.java:746)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by mousebird** [comment]
Are you on the latest version?

**Comment by msgrasser** [comment]
Nope, I wasn't. After updating to the latest version, this bug appears to have been resolved. Sorry for the confusion, and thanks for the tip!
