### ISSUE TITLE
[Android] Qui a few crashes in MaplyBaseController (from public app)

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#727]
I am getting quite a few of these from my production deployment.

It spreads "nicely" across devices and OSs.

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ironbird.fav2/com.ironbird.fav2.EditFlightPlanActivity}: java.lang.NullPointerException: Attempt to read from field 'javax.microedition.khronos.egl.EGLDisplay com.mousebird.maply.MaplyRenderer.display' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3151)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3261)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5205)
       at android.app.ActivityThread.access$1100(ActivityThread.java:219)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1741)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6939)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
Caused by java.lang.NullPointerException: Attempt to read from field 'javax.microedition.khronos.egl.EGLDisplay com.mousebird.maply.MaplyRenderer.display' on a null object reference
       at com.mousebird.maply.MaplyBaseController.setEGLContext(MaplyBaseController.java:744)
       at com.mousebird.maply.MaplyBaseController.shutdown(MaplyBaseController.java:403)
       at com.mousebird.maply.MapController.shutdown(MapController.java:174)
       at com.ironbird.fav2.map.MovingMap.shutdown(MovingMap.java:1053)
       at com.ironbird.fav2.fragments.fp_edit.NavEditorMapFrgmnt.onDestroyView(NavEditorMapFrgmnt.java:477)
       at android.support.v4.app.Fragment.performDestroyView(Fragment.java:2167)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1090)
       at android.support.v4.app.FragmentManagerImpl.removeFragment(FragmentManager.java:1294)
       at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:708)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1562)
       at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:330)
       at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:511)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1264)
       at android.app.Activity.performStart(Activity.java:6647)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3114)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3261)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5205)
       at android.app.ActivityThread.access$1100(ActivityThread.java:219)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1741)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6939)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

**Comment by mousebird** [comment]
Added guard code.
