### ISSUE TITLE
[Android] TimeOutException (live application)

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#728]
Strange crash report.

I am just getting this:
```
Fatal Exception: java.util.concurrent.TimeoutException: android.view.ThreadedRenderer.finalize() timed out after 10 seconds
       at android.view.ThreadedRenderer.nDeleteProxy(ThreadedRenderer.java)
       at android.view.ThreadedRenderer.finalize(ThreadedRenderer.java:412)
       at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:191)
       at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:174)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by mousebird** [comment]
I don't think that's in the toolkit.

Moreover, it doesn't look like it can be fixed:
http://stackoverflow.com/questions/24021609/how-to-handle-java-util-concurrent-timeoutexception-android-os-binderproxy-fin

**Comment by jmcazaux** [comment]
Let's park it then, it was just one instance, but I am not explicitly calling "finalize()" in any part of the application.

**Comment by mousebird** [comment]
That's part of the garbage collection.

**Comment by jmcazaux** [comment]
Yes, I know.
Let's close it then. I am not feeling in the mood for fixing bugs Google could not ;).
