### ISSUE TITLE
[Android] NPE when adding markers (live app)

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#729]
I had one occurence of the bug below... 
```
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'java.util.TreeMap$Node java.util.TreeMap$Node.left' on a null object reference
       at java.util.TreeMap.rotateLeft(TreeMap.java:525)
       at java.util.TreeMap.rebalance(TreeMap.java:479)
       at java.util.TreeMap.find(TreeMap.java:324)
       at java.util.TreeMap.putInternal(TreeMap.java:240)
       at java.util.TreeMap.put(TreeMap.java:186)
       at java.util.TreeSet.add(TreeSet.java:113)
       at com.mousebird.maply.TextureManager.addTexture(TextureManager.java:89)
       at com.mousebird.maply.MaplyBaseController$7.run(MaplyBaseController.java:1162)
       at com.mousebird.maply.MaplyBaseController.addTask(MaplyBaseController.java:988)
       at com.mousebird.maply.MaplyBaseController.addScreenMarkers(MaplyBaseController.java:1192)
       at com.ironbird.fav2.map.style.ComponentStyle.buildMarkerObjects(ComponentStyle.java:571)
       at com.ironbird.fav2.map.style.ComponentStyle.buildObjects(ComponentStyle.java:438)
       at com.mousebird.maply.MapboxVectorTileSource$1.run(MapboxVectorTileSource.java:133)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by mousebird** [comment]
Added locking code.
