### ISSUE TITLE
[Android] NPE on long press interaction (live app)

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#730]
This is coming from the live app
```
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'boolean com.mousebird.maply.MapGestureHandler$ScaleListener.isActive' on a null object reference
       at com.mousebird.maply.MapGestureHandler$GestureListener.onLongPress(MapGestureHandler.java:292)
       at android.view.GestureDetector.dispatchLongPress(GestureDetector.java:809)
       at android.view.GestureDetector.access$200(GestureDetector.java:46)
       at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:305)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7225)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by mousebird** [comment]
Added guard code.
