### ISSUE TITLE
[Android] NPE on MapView.animate (live application)

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#731]
```
Fatal Exception: java.lang.NullPointerException
       at com.mousebird.maply.MapView.animate(MapView.java:102)
       at com.mousebird.maply.MaplyRenderer.doRender(MaplyRenderer.java:107)
       at com.mousebird.maply.RendererWrapper.onDrawFrame(RendererWrapper.java:133)
       at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1527)
       at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1244)
```

**Comment by mousebird** [comment]
Added a lock.
