### ISSUE TITLE
[Android] Application crash (ConcurrentModificationException)

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#740]
I had the following when panning on the map.
```
09-25 08:36:49.294 22857-22947/com.ironbird.fav2 E/AndroidRuntime: FATAL EXCEPTION: Maply Layer Thread
                                                                   Process: com.ironbird.fav2, PID: 22857
                                                                   java.util.ConcurrentModificationException
                                                                       at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
                                                                       at com.mousebird.maply.MaplyBaseController$19.run(MaplyBaseController.java:1765)
                                                                       at com.mousebird.maply.MaplyBaseController.addTask(MaplyBaseController.java:989)
                                                                       at com.mousebird.maply.MaplyBaseController.enableObjects(MaplyBaseController.java:1773)
                                                                       at com.mousebird.maply.QuadPagingLayer.tileDidLoad(QuadPagingLayer.java:514)
                                                                       at com.mousebird.maply.QuadPagingLayer$3.run(QuadPagingLayer.java:495)
                                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                       at android.os.Looper.loop(Looper.java:148)
                                                                       at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by mousebird** [comment]
Copying into an array so we're not modifying things on different threads.
Should be fixed.
