### ISSUE TITLE
Binary XML crash

### ISSUE THREAD

**Issue by mousebird** [mousebird/WhirlyGlobe#793]
Problem starting an app as follows.

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.reelsonar.ibobber/com.reelsonar.ibobber.ActiveUsersGlobeActivity}: android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class fragment
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
            at android.app.ActivityThread.-wrap12(ActivityThread.java)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:154)
            at android.app.ActivityThread.main(ActivityThread.java:6077)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
     Caused by: android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class fragment
     Caused by: android.view.InflateException: Binary XML file line #8: Error inflating class fragment
    Caused by: android.app.Fragment$InstantiationException: Trying to instantiate a class com.reelsonar.ibobber.WhirlyGlobeFragment that is not a Fragment
            at android.app.Fragment.instantiate(Fragment.java:617)
            at android.app.Fragment.instantiate(Fragment.java:593)
            at android.app.FragmentManagerImpl.onCreateView(FragmentManager.java:2302)
            at android.app.FragmentController.onCreateView(FragmentController.java:98)
            at android.app.Activity.onCreateView(Activity.java:5884)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:777)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
            at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
            at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:414)
            at android.app.Activity.setContentView(Activity.java:2414)
            at com.reelsonar.ibobber.ActiveUsersGlobeActivity.onCreate(ActiveUsersGlobeActivity.java:14)
            at android.app.Activity.performCreate(Activity.java:6664)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
            at android.app.ActivityThread.-wrap12(ActivityThread.java)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:154)
            at android.app.ActivityThread.main(ActivityThread.java:6077)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
     Caused by: java.lang.ClassCastException
            at android.app.Fragment.instantiate(Fragment.java:618)
            at android.app.Fragment.instantiate(Fragment.java:593)
            at android.app.FragmentManagerImpl.onCreateView(FragmentManager.java:2302)
            at android.app.FragmentController.onCreateView(FragmentController.java:98)
            at android.app.Activity.onCreateView(Activity.java:5884)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:777)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
            at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
            at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:414)
            at android.app.Activity.setContentView(Activity.java:2414)
            at com.reelsonar.ibobber.ActiveUsersGlobeActivity.onCreate(ActiveUsersGlobeActivity.java:14)
            at android.app.Activity.performCreate(Activity.java:6664)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
            at android.app.ActivityThread.-wrap12(ActivityThread.java)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:154)
            at android.app.ActivityThread.main(ActivityThread.java:6077)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by mousebird** [comment]
Need to extend FragmentActivity rather than Activity.
