### ISSUE TITLE
Android RemoteTileSource crash

### ISSUE THREAD

**Issue by hneil** [mousebird/WhirlyGlobe#853]
The following crash was reported in Google Play:

java.lang.NullPointerException
	at com.mousebird.maply.RemoteTileSource$ConnectionTask.onFailure(RemoteTileSource.java:211)
	at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:185)
	at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:838)

**Comment by mousebird** [comment]
I put in some guard code so this should disappear.
