### ISSUE TITLE
[Android] NPE when shutting down the map

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#881]
`java.lang.NullPointerException: Attempt to invoke interface method 'void com.mousebird.maply.QuadPagingLayer$PagingInterface.clear()' on a null object reference
at com.mousebird.maply.QuadPagingLayer.shutdown(QuadPagingLayer.java:181)
at com.mousebird.maply.LayerThread$6.run(LayerThread.java:274)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at android.os.HandlerThread.run(HandlerThread.java:61)`

**Comment by jmcazaux** [comment]
As I have switched to develop it seems this does not happen anymore...
