### ISSUE TITLE
[Android] NPE when shutting down the map (issue in production)

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#918]
I am seeing quite a lot of the below with the last version of the code
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'void com.mousebird.maply.QuadPagingLayer$PagingInterface.clear()' on a null object reference
       at com.mousebird.maply.QuadPagingLayer.shutdown(QuadPagingLayer.java:181)
       at com.mousebird.maply.LayerThread$6.run(LayerThread.java:274)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by jmcazaux** [comment]
There was another issue at another place in the code that I have fixed in the same branch.

Without these 2 fixes, I see NPEs when shutting down the map.
