### ISSUE TITLE
[Android] NPE when rendering Mapbox vectors (issue in production)

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#919]
I am getting quite a lot of these from production.

```
Fatal Exception: java.lang.NullPointerException
       at com.mousebird.maply.MapboxVectorTileSource.processData(MapboxVectorTileSource.java:151)
       at com.mousebird.maply.MapboxVectorTileSource$1.run(MapboxVectorTileSource.java:193)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:146)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by jmcazaux** [comment]
My app's "crash free users" percentage is taking a real hit because of this one...

A solution would be much appreciated.

**Comment by mousebird** [comment]
Same as the other bug.  It's sort of a race condition.
Should be fixed.
