### ISSUE TITLE
[Android] NPE when getting MB tile (issue in production)

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#920]
I am getting this quite a lot from production.
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] com.mousebird.maply.MBTiles.getDataTile(com.mousebird.maply.MaplyTileID)' on a null object reference
       at com.mousebird.maply.MapboxVectorTileSource$1.run(MapboxVectorTileSource.java:191)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by mousebird** [comment]
Looks like a race condition between the explicit shutdown and any threads that may still be going.
I've put in a check.
