### ISSUE TITLE
[Android] Another crash in production

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#934]
I am getting this error a bit from production.

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.contains(java.lang.CharSequence)' on a null object reference
       at com.mousebird.maply.RemoteTileSource$ConnectionTask.onFailure(RemoteTileSource.java:216)
       at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:185)
       at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:833)
```

**Comment by jmcazaux** [comment]
I see this quite a bit now.

Would be great if it could get a bit of attention.

**Comment by mousebird** [comment]
Because the error message is null.  That's just.... weird.
Anyway, checking in the next push.
