### ISSUE TITLE
[Android] NPE in RenderWrapper.onDrawFrame

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#936]
I see some NPE coming from production in the RenderWrapper:
```
Fatal Exception: java.lang.NullPointerException
       at com.mousebird.maply.RendererWrapper.onDrawFrame(RendererWrapper.java:135)
       at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1531)
       at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1248)
```

**Comment by mousebird** [comment]
I think the only way this can happen is if the renderer is shut down before it can start.  I've put in some guard code.  Look for that in the next push.
