### ISSUE TITLE
[Android] Production crash

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#949]
Note sure when this happens, but I had a handful of occirences.

```
Fatal Exception: java.lang.NullPointerException
       at com.mousebird.maply.LayerThread.scheduleLateUpdate(LayerThread.java:489)
       at com.mousebird.maply.LayerThread.viewUpdated(LayerThread.java:531)
       at com.mousebird.maply.View.runViewUpdates(View.java:109)
       at com.mousebird.maply.MapView.setLoc(MapView.java:139)
       at com.mousebird.maply.MapAnimateTranslate.updateView(MapAnimateTranslate.java:79)
       at com.mousebird.maply.MapView.animate(MapView.java:109)
       at com.mousebird.maply.MaplyRenderer.doRender(MaplyRenderer.java:107)
       at com.mousebird.maply.RendererWrapper.onDrawFrame(RendererWrapper.java:158)
       at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1569)
       at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1275)
```

**Comment by mousebird** [comment]
I've put some guard code in that should show up in the next update.
