### ISSUE TITLE
[Android] Crash when connecting to remote tile source

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#950]
The vast majority of my users use local tile sources, but out of teh very few who do use a remote source, I get a fes of these:
```
Fatal Exception: java.lang.NullPointerException
       at com.mousebird.maply.RemoteTileSource$ConnectionTask.onFailure(RemoteTileSource.java:216)
       at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:185)
       at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:841)
```

**Comment by mousebird** [comment]
This one was recently fixed.  You should see it in the latestion.
