### ISSUE TITLE
[Android] NPE in LayerThread.scheduleLateUpdate

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#958]
```
Fatal Exception: java.lang.NullPointerException
       at com.mousebird.maply.LayerThread.scheduleLateUpdate(LayerThread.java:489)
       at com.mousebird.maply.LayerThread.viewUpdated(LayerThread.java:533)
       at com.mousebird.maply.View.runViewUpdates(View.java:109)
       at com.mousebird.maply.MapView.setLoc(MapView.java:139)
       at com.mousebird.maply.MapAnimateTranslate.updateView(MapAnimateTranslate.java:79)
       at com.mousebird.maply.MapView.animate(MapView.java:109)
       at com.mousebird.maply.MaplyRenderer.doRender(MaplyRenderer.java:107)
       at com.mousebird.maply.RendererWrapper.onDrawFrame(RendererWrapper.java:158)
       at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1557)
       at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1263)
```

**Comment by mousebird** [comment]
This one should already be fixed.  Line 489 is an if statement.
