### ISSUE TITLE
[Android] Unsatisfied link issue

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#984]
I am getting a few of these (not many users, but seems consistent for them):

```
Fatal Exception: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/mnt/expand/4ca7be99-e010-43f1-9090-41a480f94d81/app/com.ironbird.fav2-1/base.apk"],nativeLibraryDirectories=[/mnt/expand/4ca7be99-e010-43f1-9090-41a480f94d81/app/com.ironbird.fav2-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libgnustl_shared.so"
       at java.lang.Runtime.loadLibrary(Runtime.java:367)
       at java.lang.System.loadLibrary(System.java:1076)
       at com.mousebird.maply.MaplyBaseController.<init>(MaplyBaseController.java:289)
       at com.mousebird.maply.MapController.<init>(MapController.java:77)
       at com.ironbird.fav2.map.MovingMap.<init>(MovingMap.java:676)
       at com.ironbird.fav2.MovingMapActivity.onLoadResources(MovingMapActivity.java:538)
       at com.ironbird.fav2.FARootActivity.onCreate(FARootActivity.java:54)
       at com.ironbird.fav2.FAClientActivity.onCreate(FAClientActivity.java:190)
       at com.ironbird.fav2.NavActivity.onCreate(NavActivity.java:274)
       at com.ironbird.fav2.MovingMapActivity.onCreate(MovingMapActivity.java:626)
       at android.app.Activity.performCreate(Activity.java:6270)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2519)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2654)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1488)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5728)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:749)
```

**Comment by mousebird** [comment]
I know we're including libgnustl_shared, but can you check that the arm64 version is making it into your own APK?  That's all I can think to look for.

**Comment by jmcazaux** [comment]
Sure, how can I check that?

**Comment by stevesaildrone** [comment]
The APK is just a zip file.  You can unzip it and poke through the contents.  Check that the same libraries are in the architecture directories (e.g. x86)

**Comment by mousebird** [comment]
The APK is just a zip file. You can unzip it and poke through the contents. Check that the same libraries are in the architecture directories (e.g. x86)

**Comment by jmcazaux** [comment]
All 3 libs subdirs (armeabi, armeabi-v7a, x86) all contain the same files (libMaply.so and libgnustl_shared.so)...

**Comment by mousebird** [comment]
That's what should be there.  I don't know what could be causing this.
