### ISSUE TITLE
[Android] NPE in LayoutLayer.startLayer (LayoutLayer.java:46)

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#992]
I am getting quite a few of these from production.

Here is a stacktrace...

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mousebird.maply.LayerThread.addWatcher(com.mousebird.maply.LayerThread$ViewWatcherInterface)' on a null object reference
       at com.mousebird.maply.LayoutLayer.startLayer(LayoutLayer.java:46)
       at com.mousebird.maply.LayerThread$5.run(LayerThread.java:260)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by mousebird** [comment]
I've added guard code here.
